[package]
name = "taxer_csv"
version = "0.1.0-alpha.0"
edition = "2024"
license-file = "LICENSE"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
