from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = true
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = [
  "main",
]
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "cargo build --release",
  "cargo test",
  "cargo clippy",
  "cargo fmt --check",
  "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
  "cargo set-version {{version|0.0.1}}",
  "git add Cargo.toml Cargo.lock",
  "cog commit chore 'release {{version|0.0.1}}' release",
]
post_bump_hooks = [
  "cargo set-version {{version|0.0.1+patch}}-alpha.0",
  "git add Cargo.toml Cargo.lock",
  "cog commit chore 'prepare development version {{version|0.0.1+patch}}' release"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
