from_latest_tag = false
ignore_merge_commits = false
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "cargo build --release",
  "cargo test",
  "cargo clippy",
  "cargo fmt --check",
  "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
  "cargo bump {{version|0.0.1}}",
]
post_bump_hooks = [
  "cargo bump {{version|0.0.1}}-alpha.0",
  "cog commit chore 'prepare development version {{version}}' release"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
